public with sharing class Assignment_4_3 {
    public Integer num1, num2, num3;
    public Assignment_4_3() {
        this.num1 = 10;
        this.num2 = 20;
        this.num3 = 30;
    }
    public Assignment_4_3(Integer num1, Integer num2, Integer num3) {
        this.num1 = num1;
        this.num2 = num2;
        this.num3 = num3;
    }
}

// Assignment_4_3 assignInstance1 = new Assignment_4_3();
// System.debug(assignInstance1.num1 + ', ' + assignInstance1.num2 + ', ' + assignInstance1.num3);

// Assignment_4_3 assignInstance2 = new Assignment_4_3(100, 200, 300);
// System.debug(assignInstance2.num1 + ', ' + assignInstance2.num2 + ', ' + assignInstance2.num3);